version: "3.3"
 
services:

# TRAEFIK MAGIC
  traefik:
    image: traefik:1.4
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: traefik-config
        target: /etc/traefik/traefik.toml
    deploy:
      placement:
        constraints:
          - node.role == manager

# NODE.JS APP
  nodejs:
    image: danielprietsch/nodejs
    volumes:
      - /etc/docker/volumes/NodeApp:/data

    networks:
      - traefik-net
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.port=3000"
        - "traefik.backend=/"
        - "traefik.frontend.rule=Path:/"
 
networks:
  traefik-net:
    driver: overlay
 
configs:
  traefik-config:
    file: config.toml
