---
 - name: restart ntp
   service:
     name: "{{ ntp_daemon }}"
     state: restarted
   when: ntp_enabled

 - name: restart syslog
   service:
     name: rsyslog
     state: restarted
   when: ntp_enabled

